name: Notify new upstream release
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0/4 * * 1-5"

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm init --yes
      - run: npm install semver

      - name: Check for new release branch
        id: new-release
        uses: actions/github-script@v5
        with:
          result-encoding: string
          script: |
            const semver = require('semver');

            let nextRelease = undefined;
            try {
              const { data: latestRelease } = await github.rest.repos.getLatestRelease({
                owner: 'microsoft',
                repo: 'vscode'
              });

              const releaseTag = latestRelease.tag_name;
              const nextReleaseTag = semver.inc(releaseTag, 'minor');
              nextRelease = `release/${semver.major(nextReleaseTag)}.${semver.minor(nextReleaseTag)}`;
              console.log(nextRelease);
            } catch (e) {
              console.error(e);
              return false;
            }

            let upstreamReleaseBranch = undefined;
            try {
              const response = await github.rest.repos.getBranch({
                owner: 'microsoft',
                repo: 'vscode',
                branch: nextRelease
              });
              upstreamReleaseBranch = reponse.data;
              console.log(upstreamReleaseBranch);
            } catch (e) {
              console.error(e);
              return false;
            }

            let releaseBranch = undefined;
            try {
              const response = await github.rest.repos.getBranch({
                owner: 'gitpod-io',
                repo: 'openvscode-server',
                branch: nextRelease
              });
              releaseBranch = reponse.data;
            } catch (e) {
              console.log(e);
            }

            // If we already created the release branch in openvscode-server, don't create a notification
            return releaseBranch ? false : true;

      - name: Slack Notification
        if: steps.new-release.outputs.result == 'true'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: New vscode release branch created
          SLACK_MESSAGE: 'Start preparing for a new release :exclamation:'
